### ISSUE TITLE
Model Inference: eos4x30 22.05.2024

### ISSUE THREAD

**Issue by GemmaTuron** [ersilia-os/ersilia-self-service#22]
### Model

3D pharmacophore descriptor - eos4x30

### Molecules

O=C1C(C2=CC=C(OCO3)C3=C2)=C(C)OC4=C1C=C(CCC)C(OC(C)C)=C4

**Comment by GemmaTuron** [comment]
@jmassardo 

In this case, the model is fetched from docker but github actions does not seem to like it. Is that due to the model itself (which works locally with Docker) or the installation?
```
Error message:

Error while fetching server API version: Not supported URL scheme http+docker
If this error message is not helpful, open an issue at:
 - https://github.com/ersilia-os/ersilia
Or feel free to reach out to us at:
 - hello[at]ersilia.io

If you haven't, try to run your command in verbose mode (-v in the CLI)
 - You will find the console log file in: /home/runner/eos/current.log
```

**Comment by GemmaTuron** [comment]
hmm I don't understand why it is pulling from docker then, @DhanshreeA you did not do any work on this yet right?

**Comment by DhanshreeA** [comment]
Umm the action simply runs `ersilia -v fetch` which by default fetches from Docker. The only time it resorts to fetching through github is when there is no docker image available for the given model, or through the use of a `from_github` flag.

However, this issue does not seem to be from ersilia (at least not directly), this seems to be an upstream [issue](https://github.com/docker/docker-py/issues/3256) from docker_py. I'll look into triaging this asap because I think it can potentially crash during all model fetches.

**Comment by GemmaTuron** [comment]
omg seems they created a bug with the latest release, do we maybe pin requests to 2.31? if I understood the thread that seems the issue. Let me know @DhanshreeA if that is the problem

**Comment by DhanshreeA** [comment]
@GemmaTuron yep that seems to be the issue. Just checked the [requests version](https://productionresultssa16.blob.core.windows.net/actions-results/365b047c-c0c3-4f70-adfa-5d5c3525883f/workflow-job-run-eae12cd1-4e5a-52a1-5c89-b0ff3b6a9843/logs/job/job-logs.txt?rsct=text%2Fplain&se=2024-05-23T10%3A52%3A10Z&sig=1GmXxpuKLqFeZg%2B8nLeZ9sVSBivmsgYnSjcRDMP%2BkLU%3D&sp=r&spr=https&sr=b&st=2024-05-23T10%3A42%3A05Z&sv=2021-12-02) installed in the environment for this run and et voila!, it is 2.32.2. I'll add a specific dep for 2.31 and re run this action.

**Comment by DhanshreeA** [comment]
Okay seems like that fixed it. :)

**Comment by jmassardo** [comment]
YAY!!! I'm glad it was a simple fix!
